Repository entando/entando-plugin-jpseo, pull requests merged in 2020-11, with the labels that each got.

#20 ENG-1401: Fix bug on Mapping Manager
  pom.xml
  src/main/java/org/entando/entando/plugins/jpseo/aps/system/services/mapping/SeoMappingManager.java
  src/test/java/org/entando/entando/plugins/jpseo/AllTests.java
  src/test/java/org/entando/entando/plugins/jpseo/aps/system/services/mapping/SeoMappingManagerIntegrationTest.java
Labels: approved, size/L

#22 ENG-1276 add widget category field
  pom.xml
  src/main/resources/sql/plugins/jpseo/port_data_production.sql
Labels: approved, size/XS

#24 ENG-1514: Improvement of friendlycode validation
  pom.xml
  src/main/java/org/entando/entando/plugins/jpseo/aps/system/services/controller/control/RequestValidator.java
  src/main/java/org/entando/entando/plugins/jpseo/aps/system/services/mapping/ISeoMappingManager.java
  src/main/java/org/entando/entando/plugins/jpseo/aps/system/services/mapping/SeoMappingManager.java
  src/main/java/org/entando/entando/plugins/jpseo/aps/system/services/mapping/cache/ISeoMappingCacheWrapper.java
  src/main/java/org/entando/entando/plugins/jpseo/aps/system/services/mapping/cache/SeoMappingCacheWrapper.java
  src/main/java/org/entando/entando/plugins/jpseo/apsadmin/portal/PageActionAspect.java
  src/main/java/org/entando/entando/plugins/jpseo/web/page/SeoPageController.java
  src/main/java/org/entando/entando/plugins/jpseo/web/page/validator/SeoPageValidator.java
  src/main/resources/spring/plugins/jpseo/aps/baseManagersConfig.xml
  src/test/java/org/entando/entando/aps/system/services/controller/control/SeoRequestValidatorIntegrationTest.java
  src/test/java/org/entando/entando/plugins/jpseo/AllTests.java
  src/test/java/org/entando/entando/plugins/jpseo/aps/system/services/mapping/SeoMappingManagerIntegrationTest.java
  src/test/java/org/entando/entando/plugins/jpseo/apsadmin/portal/PageActionIntegrationTest.java
  src/test/java/org/entando/entando/plugins/jpseo/web/page/2_POST_valid_friendly_code.json
  src/test/java/org/entando/entando/plugins/jpseo/web/page/2_PUT_invalid_friendly_code.json
  src/test/java/org/entando/entando/plugins/jpseo/web/page/3_POST_invalid.json
  src/test/java/org/entando/entando/plugins/jpseo/web/page/SeoPageControllerIntegrationTest.java
Labels: approved, size/XL

#23 ENG-1512: Added extra param "csp.header.extraConfig"
  src/test/config/conf/systemParams.properties
Labels: approved, size/XS

#25 ENG-1512: Update BOM and snapshot version
  pom.xml
Labels: approved, size/XS
