Repository entando/entando-plugin-jpseo, pull requests merged in 2020-10, with the labels that each got.

#17 ENG-1348-Update-core-parent
  pom.xml
Labels: approved, size/XS

#15 ENG-1244 widgetcatalog readonlyDefaultConfig field added
  src/main/resources/sql/plugins/jpseo/port_data_production.sql
Labels: approved, size/XS

#14 ENG-531: Core upgrade for redis integration
  pom.xml
  src/main/java/org/entando/entando/plugins/jpseo/aps/system/services/metatag/MetatagCatalog.java
  src/main/java/org/entando/entando/plugins/jpseo/aps/system/services/page/SeoPageService.java
  src/main/resources/spring/plugins/jpseo/aps/baseManagersConfig.xml
  src/test/java/org/entando/entando/plugins/jpseo/apsadmin/portal/PageSettingsActionAspectTest.java
Labels: approved, size/M

#18 ENG-1369: Adapt seo plugin to AppEngine vulnerabilities changes
  src/main/java/org/entando/entando/plugins/jpseo/aps/system/services/controller/control/RequestValidator.java
  src/main/java/org/entando/entando/plugins/jpseo/aps/system/services/linkresolver/LinkResolverManager.java
  src/main/java/org/entando/entando/plugins/jpseo/aps/system/services/mapping/ISeoMappingManager.java
  src/main/java/org/entando/entando/plugins/jpseo/aps/system/services/mapping/SeoMappingDAO.java
  src/main/java/org/entando/entando/plugins/jpseo/aps/system/services/mapping/SeoMappingManager.java
  src/main/java/org/entando/entando/plugins/jpseo/aps/system/services/mapping/cache/ISeoMappingCacheWrapper.java
  src/main/java/org/entando/entando/plugins/jpseo/aps/system/services/mapping/cache/SeoMappingCacheWrapper.java
  src/main/java/org/entando/entando/plugins/jpseo/aps/system/services/metatag/MetatagCatalog.java
  src/main/java/org/entando/entando/plugins/jpseo/aps/system/services/metatag/MetatagDOM.java
  src/main/java/org/entando/entando/plugins/jpseo/aps/system/services/page/SeoPageDAO.java
  src/main/java/org/entando/entando/plugins/jpseo/aps/system/services/page/SeoPageExtraConfigDOM.java
  src/main/java/org/entando/entando/plugins/jpseo/aps/system/services/page/SeoPageService.java
  src/main/java/org/entando/entando/plugins/jpseo/aps/system/services/url/URLManager.java
  src/main/java/org/entando/entando/plugins/jpseo/aps/system/sitemap/SitemapAction.java
  src/main/java/org/entando/entando/plugins/jpseo/aps/tags/ContentTag.java
  src/main/java/org/entando/entando/plugins/jpseo/aps/tags/CurrentPageTag.java
  src/main/java/org/entando/entando/plugins/jpseo/aps/tags/PageInfoTag.java
  src/main/java/org/entando/entando/plugins/jpseo/aps/tags/SeoMetatagCatalogTag.java
  src/main/java/org/entando/entando/plugins/jpseo/aps/tags/SeoMetatagTag.java
  src/main/java/org/entando/entando/plugins/jpseo/aps/tags/SeoMetatagsTag.java
  src/main/java/org/entando/entando/plugins/jpseo/aps/tags/SiteMapTag.java
  src/main/java/org/entando/entando/plugins/jpseo/apsadmin/content/helper/ContentActionHelperAspect.java
  src/main/java/org/entando/entando/plugins/jpseo/apsadmin/portal/PageActionAspect.java
  src/main/java/org/entando/entando/plugins/jpseo/apsadmin/portal/PageSettingsActionAspect.java
  src/main/java/org/entando/entando/plugins/jpseo/apsadmin/portal/SeoPageAction.java
  src/main/java/org/entando/entando/plugins/jpseo/apsadmin/portal/SeoPageSettingsAction.java
  src/main/java/org/entando/entando/plugins/jpseo/web/page/ISeoPageController.java
  src/main/java/org/entando/entando/plugins/jpseo/web/page/SeoPageController.java
  src/main/java/org/entando/entando/plugins/jpseo/web/page/validator/SeoPageValidator.java
  src/test/java/org/entando/entando/plugins/jpseo/apsadmin/portal/PageSettingsActionAspectTest.java
Labels: approved, size/L

#16 ENG-1180: Improvement of support for clustered environments
  pom.xml
  src/main/java/org/entando/entando/plugins/jpseo/aps/system/services/mapping/SeoMappingManager.java
  src/main/java/org/entando/entando/plugins/jpseo/aps/system/services/mapping/cache/ISeoMappingCacheWrapper.java
  src/main/java/org/entando/entando/plugins/jpseo/aps/system/services/mapping/cache/SeoMappingCacheWrapper.java
  src/main/java/org/entando/entando/plugins/jpseo/aps/system/services/metatag/MetatagCatalog.java
  src/test/java/org/entando/entando/plugins/jpseo/apsadmin/portal/PageSettingsActionAspectTest.java
Labels: approved, size/M

#19 ENG-1276 widget rename
  src/main/resources/sql/plugins/jpseo/port_data_production.sql
Labels: size/XS

#21 ENG-1244 refactor to readonly page widget config
  pom.xml
  src/main/resources/sql/plugins/jpseo/port_data_production.sql
Labels: approved, size/XS
