Repository entando/entando-plugin-jpseo, pull requests merged in 2020-07, with the labels that each got.

#1 ENG-827 got tests working
  .gitignore
  README.md
  pom.xml
Labels: size/M

#2 ENG-877: Add LICENSE file
  LICENSE
Labels: size/L

#3 ENG-773 APIs with SEO attributes added
  pom.xml
  src/main/java/org/entando/entando/plugins/jpseo/aps/system/services/page/PageMetatag.java
  src/main/java/org/entando/entando/plugins/jpseo/aps/system/services/page/SeoPageDto.java
  src/main/java/org/entando/entando/plugins/jpseo/aps/system/services/page/SeoPageService.java
  src/main/java/org/entando/entando/plugins/jpseo/web/page/ISeoPageController.java
  src/main/java/org/entando/entando/plugins/jpseo/web/page/SeoPageController.java
  src/main/java/org/entando/entando/plugins/jpseo/web/page/model/SeoData.java
  src/main/java/org/entando/entando/plugins/jpseo/web/page/model/SeoDataByLang.java
  src/main/java/org/entando/entando/plugins/jpseo/web/page/model/SeoMetaTag.java
  src/main/java/org/entando/entando/plugins/jpseo/web/page/model/SeoPageRequest.java
  src/main/java/org/entando/entando/plugins/jpseo/web/page/validator/SeoPageValidator.java
  src/main/resources/spring/plugins/jpseo/aps/baseManagersConfig.xml
  src/test/config/conf/systemParams.properties
  src/test/java/org/entando/entando/plugins/jpseo/AllTests.java
  src/test/java/org/entando/entando/plugins/jpseo/web/page/SeoPageControllerTest.java
Labels: approved, size/XXL

#5 ENG-944 Changing integration tests for Seo API permissions
  pom.xml
  src/main/java/org/entando/entando/plugins/jpseo/aps/system/services/page/SeoPageService.java
  src/main/java/org/entando/entando/plugins/jpseo/web/page/SeoPageController.java
  src/main/java/org/entando/entando/plugins/jpseo/web/page/model/SeoData.java
  src/test/java/org/entando/entando/plugins/jpseo/AllTests.java
  src/test/java/org/entando/entando/plugins/jpseo/utils/stubhelper/SeoStubHelper.java
  src/test/java/org/entando/entando/plugins/jpseo/web/page/1_POST_valid.json
  src/test/java/org/entando/entando/plugins/jpseo/web/page/1_POST_valid_empty_fields.json
  src/test/java/org/entando/entando/plugins/jpseo/web/page/2_POST_valid.json
  src/test/java/org/entando/entando/plugins/jpseo/web/page/2_PUT_valid.json
  src/test/java/org/entando/entando/plugins/jpseo/web/page/SeoPageControllerIntegrationTest.java
Labels: approved, size/XL

#4 ENG-948 fixed issues with Bean conflicts
  pom.xml
  src/main/java/org/entando/entando/plugins/jpseo/aps/system/services/page/SeoPageService.java
  src/main/java/org/entando/entando/plugins/jpseo/web/page/SeoPageController.java
Labels: approved, size/XS

#7 Eng 950 removed admin console dependency
  OWNERS
  OWNERS_ALIASES
  pom.xml
Labels: approved, size/L

#9 ENG-773 support for not mandatory fields
  src/main/java/org/entando/entando/plugins/jpseo/aps/system/services/page/SeoPageService.java
  src/main/java/org/entando/entando/plugins/jpseo/aps/tags/CurrentPageTag.java
  src/main/java/org/entando/entando/plugins/jpseo/aps/tags/SeoMetatagTag.java
  src/test/java/org/entando/entando/plugins/jpseo/web/page/1_POST_valid_empty_fields_2.json
  src/test/java/org/entando/entando/plugins/jpseo/web/page/2_PUT_valid_no_metatag.json
  src/test/java/org/entando/entando/plugins/jpseo/web/page/SeoPageControllerIntegrationTest.java
Labels: approved, size/XL
