Repository entando/entando-plugin-jpseo, pull requests merged in 2021-02, with the labels that each got.

#29 ENG-1745: Restructuring of appengine tests
  pom.xml
  src/test/java/org/entando/entando/aps/system/services/controller/control/SeoRequestValidatorIntegrationTest.java
  src/test/java/org/entando/entando/plugins/jpseo/AllTests.java
  src/test/java/org/entando/entando/plugins/jpseo/PluginConfigTestUtils.java
  src/test/java/org/entando/entando/plugins/jpseo/aps/ApsPluginBaseTestCase.java
  src/test/java/org/entando/entando/plugins/jpseo/aps/system/services/mapping/SeoMappingManagerIntegrationTest.java
  src/test/java/org/entando/entando/plugins/jpseo/aps/system/services/metatag/MetatagCatalogueIntegrationTest.java
  src/test/java/org/entando/entando/plugins/jpseo/aps/system/services/page/SeoPageServiceTest.java
  src/test/java/org/entando/entando/plugins/jpseo/apsadmin/ApsAdminPluginBaseTestCase.java
  src/test/java/org/entando/entando/plugins/jpseo/apsadmin/content/ContentActionIntegrationTest.java
  src/test/java/org/entando/entando/plugins/jpseo/apsadmin/portal/PageActionIntegrationTest.java
  src/test/java/org/entando/entando/plugins/jpseo/apsadmin/portal/PageSettingsActionAspectTest.java
  src/test/java/org/entando/entando/plugins/jpseo/apsadmin/portal/PageSettingsActionIntegrationTest.java
  src/test/java/org/entando/entando/plugins/jpseo/web/page/SeoPageControllerIntegrationTest.java
  src/test/java/org/entando/entando/plugins/jpseo/web/page/SeoPageControllerTest.java
Labels: approved, size/XL

#30 ENG-1461 add icon to widget type in widgetcatalog
  pom.xml
  src/main/resources/sql/plugins/jpseo/port_data_production.sql
Labels: approved, size/XS

#31 ENG-1536 Changing friendly code to be multi language
  src/main/java/org/entando/entando/plugins/jpseo/aps/system/services/mapping/SeoMappingManager.java
  src/main/java/org/entando/entando/plugins/jpseo/aps/system/services/mapping/cache/SeoMappingCacheWrapper.java
  src/main/java/org/entando/entando/plugins/jpseo/aps/system/services/page/SeoPageExtraConfigDOM.java
  src/main/java/org/entando/entando/plugins/jpseo/aps/system/services/page/SeoPageMetadata.java
  src/main/java/org/entando/entando/plugins/jpseo/aps/system/services/page/SeoPageService.java
  src/main/java/org/entando/entando/plugins/jpseo/aps/system/services/url/URLManager.java
  src/main/java/org/entando/entando/plugins/jpseo/aps/tags/CurrentPageTag.java
  src/main/java/org/entando/entando/plugins/jpseo/aps/tags/SeoMetatagTag.java
  src/main/java/org/entando/entando/plugins/jpseo/aps/tags/SeoMetatagsTag.java
  src/main/java/org/entando/entando/plugins/jpseo/apsadmin/portal/PageActionAspect.java
  src/main/java/org/entando/entando/plugins/jpseo/apsadmin/portal/SeoPageActionUtils.java
  src/main/java/org/entando/entando/plugins/jpseo/web/page/SeoPageController.java
  src/main/java/org/entando/entando/plugins/jpseo/web/page/model/SeoData.java
  src/main/java/org/entando/entando/plugins/jpseo/web/page/model/SeoDataByLang.java
  src/test/java/org/entando/entando/aps/system/services/controller/control/SeoRequestValidatorIntegrationTest.java
  src/test/java/org/entando/entando/plugins/jpseo/aps/system/services/mapping/SeoMappingManagerIntegrationTest.java
  src/test/java/org/entando/entando/plugins/jpseo/aps/tags/CurrentPageTagTest.java
  src/test/java/org/entando/entando/plugins/jpseo/apsadmin/portal/PageActionIntegrationTest.java
  src/test/java/org/entando/entando/plugins/jpseo/utils/stubhelper/SeoStubHelper.java
  src/test/java/org/entando/entando/plugins/jpseo/web/page/1_POST_valid.json
  src/test/java/org/entando/entando/plugins/jpseo/web/page/2_POST_valid.json
  src/test/java/org/entando/entando/plugins/jpseo/web/page/2_POST_valid_friendly_code.json
  src/test/java/org/entando/entando/plugins/jpseo/web/page/2_PUT_invalid_friendly_code.json
  src/test/java/org/entando/entando/plugins/jpseo/web/page/2_PUT_valid.json
  src/test/java/org/entando/entando/plugins/jpseo/web/page/2_PUT_valid_meta_default_lang_true.json
  src/test/java/org/entando/entando/plugins/jpseo/web/page/2_PUT_valid_no_metatag.json
  src/test/java/org/entando/entando/plugins/jpseo/web/page/3_POST_invalid.json
  src/test/java/org/entando/entando/plugins/jpseo/web/page/SeoPageControllerIntegrationTest.java
Labels: approved, size/XL

#32 ENG-1875 Protecting against null pointer
  src/main/java/org/entando/entando/plugins/jpseo/aps/system/services/page/SeoPageService.java
  src/test/java/org/entando/entando/plugins/jpseo/web/page/4_POST_valid.json
  src/test/java/org/entando/entando/plugins/jpseo/web/page/SeoPageControllerIntegrationTest.java
Labels: approved, size/M

#33 ENG-1878 Changing request validator to find friendly code on portal-ui
  src/main/java/org/entando/entando/plugins/jpseo/aps/system/services/controller/control/RequestValidator.java
  src/test/java/org/entando/entando/aps/system/services/controller/control/SeoRequestValidatorIntegrationTest.java
Labels: approved, size/S
